=== sdabhi23/streaming-data-pipeline/kinesis-consumer/json-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "event": {
            "type": "object",
            "properties": {
                "property": {
                    "type": "object",
                    "properties": {
                        "call_id": {
                            "type": "string",
                            "format": "uuid"
                        },
                        "call_duration": {
                            "type": "string",
                            "pattern": "^\\d+$"
                        },
                        "call_status": {
                            "type": "string",
                            "enum": [
                                "completed",
                                "ongoing",
                                "failed"
                            ]
                        }
                    },
                    "required": [
                        "call_id",
                        "call_duration",
                        "call_status"
                    ]
                },
                "super_property": {
                    "type": "object",
                    "properties": {
                        "source": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        },
                        "producer": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "timestamp": {
                            "type": "string",
                            "pattern": "^\\d+$"
                        }
                    },
                    "required": [
                        "source",
                        "type",
                        "producer",
                        "name",
                        "timestamp"
                    ]
                }
            },
            "required": [
                "property",
                "super_property"
            ]
        },
        "user": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                },
                "state": {
                    "type": "object",
                    "properties": {
                        "coins": {
                            "type": "string",
                            "pattern": "^\\d+$"
                        },
                        "is_logged_in": {
                            "type": "string",
                            "enum": [
                                "true",
                                "false"
                            ]
                        },
                        "language": {
                            "type": "string"
                        },
                        "language_mode": {
                            "type": "string"
                        },
                        "country_code": {
                            "type": "string"
                        },
                        "tz": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "coins",
                        "is_logged_in",
                        "language",
                        "language_mode",
                        "country_code",
                        "tz"
                    ]
                },
                "device_segment": {
                    "type": "string"
                }
            },
            "required": [
                "user_id",
                "state",
                "device_segment"
            ]
        },
        "platform": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "object",
                    "properties": {
                        "integer": {
                            "type": "string",
                            "pattern": "^\\d+$"
                        },
                        "string": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "integer",
                        "string"
                    ]
                },
                "code": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            },
            "required": [
                "version",
                "code",
                "type"
            ]
        },
        "geo_location": {
            "type": "null"
        },
        "device": {
            "type": "object",
            "properties": {
                "a_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "state": {
                    "type": "object",
                    "properties": {
                        "is_background": {
                            "type": "string",
                            "enum": [
                                "true",
                                "false"
                            ]
                        },
                        "is_online": {
                            "type": "string",
                            "enum": [
                                "true",
                                "false"
                            ]
                        },
                        "is_playing_music": {
                            "type": "string",
                            "enum": [
                                "true",
                                "false"
                            ]
                        }
                    },
                    "required": [
                        "is_background",
                        "is_online",
                        "is_playing_music"
                    ]
                },
                "hardware": {
                    "type": "object",
                    "properties": {
                        "model_name": {
                            "type": "string"
                        },
                        "brand_name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "model_name",
                        "brand_name",
                        "type"
                    ]
                },
                "software": {
                    "type": "object",
                    "properties": {
                        "mobile": {
                            "type": "object",
                            "properties": {
                                "version": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "version",
                                "name"
                            ]
                        },
                        "web": {
                            "type": "null"
                        }
                    },
                    "required": [
                        "mobile",
                        "web"
                    ]
                },
                "ip": {
                    "type": "object",
                    "properties": {
                        "ipv4": {
                            "type": "string",
                            "format": "ipv4"
                        },
                        "ipv6": {
                            "type": "string",
                            "format": "ipv6"
                        }
                    },
                    "required": [
                        "ipv4",
                        "ipv6"
                    ]
                },
                "system_language": {
                    "type": "string"
                },
                "system_id": {
                    "type": "string"
                }
            },
            "required": [
                "a_id",
                "state",
                "hardware",
                "software",
                "ip",
                "system_language",
                "system_id"
            ]
        },
        "session": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                }
            },
            "required": [
                "number",
                "id"
            ]
        },
        "referral": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                },
                "user_code": {
                    "type": "string"
                }
            },
            "required": [
                "user_id",
                "user_code"
            ]
        }
    },
    "required": [
        "event",
        "user",
        "platform",
        "geo_location",
        "device",
        "session",
        "referral"
    ]
}

=== sdabhi23/streaming-data-pipeline/infra/event-template.json
{
    "event": {
      "property": {
        "call_id": "abcdef12-3456-7890-abcd-ef1234567890",
        "call_duration": "45",
        "call_status": "completed"
      },
      "super_property": {
        "source": "mandir",
        "type": "purchase",
        "producer": "user",
        "name": "astrology_session_purchase",
        "timestamp": "1708700620952"
      }
    },
    "user": {
      "user_id": "567",
      "state": {
        "coins": "120",
        "is_logged_in": "false",
        "language": "en",
        "language_mode": "en",
        "country_code": "US",
        "tz": "America/New_York"
      },
      "device_segment": "42"
    },
    "platform": {
      "version": {
        "integer": "226",
        "string": "7.1.0"
      },
      "code": "com.mandir",
      "type": "iOS"
    },
    "geo_location": null,
    "device": {
      "a_id": "9abcde21-a08f-1794-96a9-a17bb227b793",
      "state": {
        "is_background": "true",
        "is_online": "false",
        "is_playing_music": "true"
      },
      "hardware": {
        "model_name": "iPhone12",
        "brand_name": "Apple",
        "type": "Mobile"
      },
      "software": {
        "mobile": {
          "version": "14",
          "name": "iOS"
        },
        "web": null
      },
      "ip": {
        "ipv4": "192.168.1.1",
        "ipv6": "2401:db00:2110:3004:0:0:0:1"
      },
      "system_language": "Spanish",
      "system_id": "c9gh5764f1761cd8"
    },
    "session": {
      "number": "5",
      "id": "c44fc60b-1730-400c-a0f6-c3f2a3537238"
    },
    "referral": {
      "user_id": "123",
      "user_code": "XYZREF123"
    }
  }
